# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TouchBase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 3.1'  
  pod 'MRArticleViewController', '~> 1.0.6'
  pod 'CHTCollectionViewWaterfallLayout'
  pod 'ASCollectionView', '1.0.3'  
  # Pods for TouchBase

end
